Code
dmbarreiro/DOEDA pull request #2
Opened 2022-05-16 13:12 UTC by ABohynDOE

I've finished the `csv2json.py`script that converts a csv file to a JSON script and I've added some more documentation

2022-05-16 14:04 UTC, dmbarreiro commented on docs/glossary.md
> +  A full-factorial $2^{k}$ contains all combinations of the levels of $k$ factors.
github's markdown does not understand late syntax, that's a pity. There are some solutions out there but nothing we can directly use. We can talk about it tomorrow but for the moment I find this OK

2022-05-16 14:15 UTC, dmbarreiro requested changes

2022-05-16 15:04 UTC, ABohynDOE commented on utils/csv2json.py
>  """
Good idea

2022-05-16 22:52 UTC, dmbarreiro approved these changes
All good for me, let's wait for @saif-analyze or @mariobecerra  review of csv2json.py
Good job!

2022-05-17 23:54 UTC, dmbarreiro commented
I will merge this already, if something needs to be adjusted we will do it later

2022-05-17 23:55 UTC, merged